# Generated by Django 4.2.6 on 2023-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_id_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Title',
            field=models.CharField(max_length=254),
        ),
    ]
